#pragma config(Sensor, dgtl1,  armLeft,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  armRight,        sensorQuadEncoder)
#pragma config(Motor,  port1,           bLeftMotor,    tmotorNone, openLoop)
#pragma config(Motor,  port2,           bRightMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fLeftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           fRightMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armLeftMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           handMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pinballMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           suckerMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lifterMotor,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true){
    motor[bLeftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
    motor[bRightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2
    motor[fLeftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
    motor[fRightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2

    motor[armLeftMotor]=vexRT[Ch3];
    motor[armRightMotor]=vexRT[Ch3];
    motor[suckerMotor]=127;
    motor[handMotor]=vexRT[Ch4];
    if (vexRT[Btn7L])
    {
       clearTimer(T1);
    	 motor[lifterMotor]=127;
    }
    if(time10[T1]>=1000 && time10[T1]<=1050)
    {
        motor[lifterMotor]=0;
        motor[pinballMotor]=127;
    }

    if(time10[T1]>=2000 && time10[T1]<=2050)
    {
        motor[pinballMotor]=0;
        motor[lifterMotor]=-127;
    }

    if(time10[T1]>=3000 && time10[T1]<=3050)
        motor[lifterMotor]=0;
  }
}
