#pragma config(Sensor, dgtl1,  head,           sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  eleft,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  eright,         sensorQuadEncoder)
#pragma config(Motor,  port2,           hlr,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           hud,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Global variables
int leftGround;
int rightGround;
int leftishGround;
int rightishGround;
int ground;
//End global variables

void wander()
{
	if(floor(time1[timer1])%15==0)
	{
	}
}

void avoid()
{
}

void remote()
{
}



task main()
{
	SensorValue[eleft] = 0;
	SensorValue[eright] = 0;
	motor[hud]=-75;
	motor[hlr]=-120;
  leftGround=SensorValue[head];
  motor[hlr]=-60;
  leftishGround=SensorValue[head];
  motor[hlr]=0;
  ground=SensorValue[head];
  motor[hlr]=60;
  rightishGround=SensorValue[head];
	motor[hlr]=120;
	rightGround=SensorValue[head];
	motor[hlr]=0;
	motor[hud]=0;
	clearTimer(timer1);


	while(true)
	{
		wander();//will make the robot randomly wander around if certain conditions are met
		avoid();//will make the robot avoid collisions
		remote();//will check remote control for instructions
	}
}
