#pragma config(Sensor, dgtl1,  head,           sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  eleft,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  eright,         sensorQuadEncoder)
#pragma config(Motor,  port2,           hlr,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           hud,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[eleft] = 0;
  SensorValue[eright] = 0;
  motor[hud]=-75;
	motor[hlr]=-127;
	int leftGround=SensorValue[head];
	motor[hlr]=



}
