#pragma config(Sensor, dgtl1,  head,           sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  eleft,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  eright,         sensorQuadEncoder)
#pragma config(Motor,  port2,           hlr,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           hud,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[eleft] = 0;
  SensorValue[eright] = 0;
  motor[hud]=-75;
	motor[hlr]=-120;
	int leftGround=SensorValue[head];
	motor[hlr]=120;
	int rightGround=SensorValue[head];
	motor[hlr]=0;
	int ground=SensorValue[head];



	while(true)
	{
		wander();//will make the robot randomly wander around if certain conditions are met
		avoid();//will make the robot avoid collisions
		remote();//will check remote control for instructions
	}

	void wander()
	{
	}

	void avoid()
	{
	}

	void remote()
	{
	}
}
